version: 1

interfaces:
  - id: trunk
    name: VLAN trunk
    device: eth1
    ipv4:
      mode: disabled
    ipv6:
      mode: disabled

  - id: guests
    name: Guests VLAN
    device: eth1.20
    vlan:
      parent: trunk
      tag: 20
    ipv4:
      mode: static
      address: 192.168.20.1/24
    ipv6:
      mode: disabled
