"""Deterministic systemd-networkd configuration generation for interfaces."""

import os
import re
import subprocess
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from kavernis.models.interface import (
    IPv4AddressMode,
    IPv6AddressMode,
    NetworkInterface,
)


class NetworkdValidationError(ValueError):
    """Raised when generated networkd configuration is unsafe or malformed."""


class NetworkdApplyError(RuntimeError):
    """Raised when a generated networkd candidate cannot be activated."""


@dataclass(frozen=True)
class NetworkdConfiguration:
    """Generated files, kept in memory until a future safe apply operation."""

    files: Mapping[str, str]


def generate(interfaces: Sequence[NetworkInterface]) -> NetworkdConfiguration:
    """Generate deterministic .network and virtual interface .netdev files."""
    ordered = sorted(interfaces, key=lambda item: item.id)
    children: dict[str, list[str]] = {interface.id: [] for interface in ordered}
    by_id = {interface.id: interface for interface in ordered}
    pairs: set[tuple[str, int]] = set()
    for interface in ordered:
        if interface.vlan is None:
            continue
        vlan = interface.vlan
        parent = by_id.get(vlan.parent)
        if (
            parent is None
            or parent.id == interface.id
            or parent.vlan is not None
            or parent.bridge is not None
        ):
            raise NetworkdValidationError(
                f"interface {interface.id}: invalid VLAN parent {vlan.parent}"
            )
        pair = (vlan.parent, vlan.tag)
        if pair in pairs:
            raise NetworkdValidationError(f"interface {interface.id}: duplicate VLAN")
        pairs.add(pair)
        children[vlan.parent].append(interface.device)

    bridges = _bridge_attachments(ordered)
    files: dict[str, str] = {}
    for interface in ordered:
        stem = f"10-kavernis-{interface.id}"
        files[f"{stem}.network"] = _render_interface(
            interface, children[interface.id], bridges.get(interface.id)
        )
        if interface.vlan is not None:
            files[f"{stem}.netdev"] = (
                f"[NetDev]\nName={interface.device}\nKind=vlan\n\n"
                f"[VLAN]\nId={interface.vlan.tag}\n"
            )
        elif interface.bridge is not None:
            stp = "yes" if interface.bridge.stp else "no"
            files[f"{stem}.netdev"] = (
                f"[NetDev]\nName={interface.device}\nKind=bridge\n\n"
                f"[Bridge]\nSTP={stp}\n"
            )
    candidate = NetworkdConfiguration(files=files)
    validate(candidate)
    return candidate


def validate(candidate: NetworkdConfiguration) -> None:
    """Validate the generated networkd candidate before any future apply step.

    systemd-networkd has no standalone, side-effect-free syntax verifier for
    .network files. This validation therefore verifies the constrained native
    syntax generated by this backend. Native service validation belongs to the
    controlled integration/apply environment.
    """
    if not candidate.files:
        raise NetworkdValidationError(
            "networkd candidate must contain at least one file"
        )

    for filename, content in candidate.files.items():
        if not re.fullmatch(r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", filename):
            raise NetworkdValidationError(f"unsafe networkd filename: {filename}")
        if "/" in filename or "\\" in filename:
            raise NetworkdValidationError(f"unsafe networkd filename: {filename}")
        if filename.endswith(".netdev"):
            if "\nKind=bridge\n" in content:
                _validate_bridge_netdev(filename, content)
            else:
                _validate_vlan_netdev(filename, content)
        elif not content.startswith("[Match]\n") or "\n[Network]\n" not in content:
            raise NetworkdValidationError(f"invalid networkd content for {filename}")
        if not content.endswith("\n"):
            raise NetworkdValidationError(
                f"networkd content must end with newline: {filename}"
            )


def apply(
    candidate: NetworkdConfiguration,
    directory: Path = Path("/etc/systemd/network"),
) -> None:
    """Install a validated candidate and ask systemd-networkd to reload it.

    Only Kavernis-owned files are replaced or removed. If networkctl cannot
    activate the candidate, the previously managed files are restored before
    the error is reported.
    """
    validate(candidate)
    previous = _managed_files(directory)
    try:
        directory.mkdir(parents=True, exist_ok=True)
        for filename, content in candidate.files.items():
            _write_atomically(directory / filename, content)
        for filename in set(previous) - set(candidate.files):
            (directory / filename).unlink()
        subprocess.run(
            ["networkctl", "reload"], check=True, capture_output=True, text=True
        )
    except (OSError, subprocess.CalledProcessError) as error:
        _restore(directory, previous)
        try:
            subprocess.run(
                ["networkctl", "reload"], check=False, capture_output=True, text=True
            )
        except OSError:
            pass
        detail = str(error)
        if isinstance(error, subprocess.CalledProcessError):
            detail = str(error.stderr).strip()
        raise NetworkdApplyError(
            f"cannot apply networkd configuration: {detail}"
        ) from error


def _managed_files(directory: Path) -> dict[str, str]:
    """Return only existing files owned by Kavernis."""
    if not directory.exists():
        return {}
    return {
        path.name: path.read_text(encoding="utf-8")
        for path in directory.iterdir()
        if path.is_file()
        and re.fullmatch(r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", path.name)
    }


def _write_atomically(path: Path, content: str) -> None:
    """Replace one native configuration file without exposing partial content."""
    descriptor, temporary_name = tempfile.mkstemp(prefix=".kavernis-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _restore(directory: Path, previous: Mapping[str, str]) -> None:
    """Restore the managed-file snapshot after an unsuccessful activation."""
    if not directory.exists():
        return
    for path in directory.iterdir():
        if path.is_file() and re.fullmatch(
            r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", path.name
        ):
            path.unlink()
    for filename, content in previous.items():
        _write_atomically(directory / filename, content)


def _validate_vlan_netdev(filename: str, content: str) -> None:
    match = re.fullmatch(
        r"\[NetDev\]\nName=([A-Za-z0-9_.-]{1,15})\nKind=vlan\n\n"
        r"\[VLAN\]\nId=([0-9]+)\n",
        content,
    )
    if match is None or match[1] in {".", ".."} or not 1 <= int(match[2]) <= 4094:
        raise NetworkdValidationError(f"invalid VLAN netdev content for {filename}")


def _bridge_attachments(interfaces: Sequence[NetworkInterface]) -> dict[str, str]:
    """Resolve validated member ids to native bridge device names."""
    by_id = {interface.id: interface for interface in interfaces}
    vlan_parents = {
        interface.vlan.parent for interface in interfaces if interface.vlan is not None
    }
    attachments: dict[str, str] = {}
    for interface in interfaces:
        if interface.bridge is None:
            continue
        if interface.vlan is not None or not interface.bridge.members:
            raise NetworkdValidationError(f"interface {interface.id}: invalid bridge")
        for member_id in interface.bridge.members:
            member = by_id.get(member_id)
            if (
                member is None
                or member.bridge is not None
                or member_id in attachments
                or member_id in vlan_parents
                or member.ipv4.mode is not IPv4AddressMode.DISABLED
                or member.ipv6.mode is not IPv6AddressMode.DISABLED
            ):
                raise NetworkdValidationError(
                    f"interface {interface.id}: invalid bridge member {member_id}"
                )
            attachments[member_id] = interface.device
    return attachments


def _validate_bridge_netdev(filename: str, content: str) -> None:
    match = re.fullmatch(
        r"\[NetDev\]\nName=([A-Za-z0-9_.-]{1,15})\nKind=bridge\n\n"
        r"\[Bridge\]\nSTP=(yes|no)\n",
        content,
    )
    if match is None or match[1] in {".", ".."}:
        raise NetworkdValidationError(f"invalid bridge netdev content for {filename}")


def _render_interface(
    interface: NetworkInterface,
    vlans: Sequence[str] = (),
    bridge: str | None = None,
) -> str:
    network_settings: list[str] = []
    ipv4_dhcp = interface.ipv4.mode is IPv4AddressMode.DHCP
    ipv6_dhcp = interface.ipv6.mode is IPv6AddressMode.DHCP6

    if interface.ipv4.mode is IPv4AddressMode.STATIC:
        if interface.ipv4.address is None:
            raise NetworkdValidationError(
                f"static IPv4 interface {interface.id} has no address"
            )
        network_settings.append(f"Address={interface.ipv4.address}")

    if interface.ipv6.mode is IPv6AddressMode.STATIC:
        if interface.ipv6.address is None:
            raise NetworkdValidationError(
                f"static IPv6 interface {interface.id} has no address"
            )
        network_settings.append(f"Address={interface.ipv6.address}")
        network_settings.append("IPv6AcceptRA=no")
    elif interface.ipv6.mode is IPv6AddressMode.SLAAC:
        network_settings.append("IPv6AcceptRA=yes")
    elif interface.ipv6.mode is IPv6AddressMode.DISABLED:
        network_settings.append("IPv6AcceptRA=no")

    if ipv4_dhcp and ipv6_dhcp:
        network_settings.append("DHCP=yes")
    elif ipv4_dhcp:
        network_settings.append("DHCP=ipv4")
    elif ipv6_dhcp:
        network_settings.append("DHCP=ipv6")

    network_settings.extend(f"VLAN={device}" for device in vlans)
    if bridge is not None:
        network_settings.extend(
            ["DHCP=no", "LinkLocalAddressing=no", f"Bridge={bridge}"]
        )

    lines = ["[Match]", f"Name={interface.device}", "", "[Network]", *network_settings]
    return "\n".join(lines) + "\n"
