"""Deterministic systemd-networkd configuration generation for interfaces."""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from kavernis.models.interface import (
    IPv4AddressMode,
    IPv6AddressMode,
    NetworkInterface,
)


class NetworkdValidationError(ValueError):
    """Raised when generated networkd configuration is unsafe or malformed."""


@dataclass(frozen=True)
class NetworkdConfiguration:
    """Generated files, kept in memory until a future safe apply operation."""

    files: Mapping[str, str]


def generate(interfaces: Sequence[NetworkInterface]) -> NetworkdConfiguration:
    """Generate one deterministic .network file per interface model."""
    files = {
        f"10-kavernis-{interface.id}.network": _render_interface(interface)
        for interface in sorted(interfaces, key=lambda item: item.id)
    }
    candidate = NetworkdConfiguration(files=files)
    validate(candidate)
    return candidate


def validate(candidate: NetworkdConfiguration) -> None:
    """Validate the generated networkd candidate before any future apply step.

    systemd-networkd has no standalone, side-effect-free syntax verifier for
    .network files. This validation therefore verifies the constrained native
    syntax generated by this backend. Native service validation belongs to the
    controlled integration/apply environment.
    """
    if not candidate.files:
        raise NetworkdValidationError(
            "networkd candidate must contain at least one file"
        )

    for filename, content in candidate.files.items():
        if not filename.startswith("10-kavernis-") or not filename.endswith(".network"):
            raise NetworkdValidationError(f"unsafe networkd filename: {filename}")
        if "/" in filename or "\\" in filename:
            raise NetworkdValidationError(f"unsafe networkd filename: {filename}")
        if not content.startswith("[Match]\n") or "\n[Network]\n" not in content:
            raise NetworkdValidationError(f"invalid networkd content for {filename}")
        if not content.endswith("\n"):
            raise NetworkdValidationError(
                f"networkd content must end with newline: {filename}"
            )


def _render_interface(interface: NetworkInterface) -> str:
    network_settings: list[str] = []
    ipv4_dhcp = interface.ipv4.mode is IPv4AddressMode.DHCP
    ipv6_dhcp = interface.ipv6.mode is IPv6AddressMode.DHCP6

    if interface.ipv4.mode is IPv4AddressMode.STATIC:
        if interface.ipv4.address is None:
            raise NetworkdValidationError(
                f"static IPv4 interface {interface.id} has no address"
            )
        network_settings.append(f"Address={interface.ipv4.address}")

    if interface.ipv6.mode is IPv6AddressMode.STATIC:
        if interface.ipv6.address is None:
            raise NetworkdValidationError(
                f"static IPv6 interface {interface.id} has no address"
            )
        network_settings.append(f"Address={interface.ipv6.address}")
        network_settings.append("IPv6AcceptRA=no")
    elif interface.ipv6.mode is IPv6AddressMode.SLAAC:
        network_settings.append("IPv6AcceptRA=yes")
    elif interface.ipv6.mode is IPv6AddressMode.DISABLED:
        network_settings.append("IPv6AcceptRA=no")

    if ipv4_dhcp and ipv6_dhcp:
        network_settings.append("DHCP=yes")
    elif ipv4_dhcp:
        network_settings.append("DHCP=ipv4")
    elif ipv6_dhcp:
        network_settings.append("DHCP=ipv6")

    lines = ["[Match]", f"Name={interface.device}", "", "[Network]", *network_settings]
    return "\n".join(lines) + "\n"
