"""Deterministic systemd-networkd configuration generation for interfaces."""

import hashlib
import os
import re
import subprocess
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path

from kavernis.models.interface import (
    IPv4AddressMode,
    IPv6AddressMode,
    NetworkInterface,
)
from kavernis.rendering import render_template
from kavernis.state.models import ArtifactDrift, ArtifactDriftKind

NETWORKD_FILE_MODE = 0o644


class NetworkdValidationError(ValueError):
    """Raised when generated networkd configuration is unsafe or malformed."""


class NetworkdApplyError(RuntimeError):
    """Raised when a generated networkd candidate cannot be activated."""


@dataclass(frozen=True)
class NetworkdConfiguration:
    """Generated files, kept in memory until a future safe apply operation."""

    files: Mapping[str, str]


@dataclass(frozen=True)
class NetworkTemplateContext:
    """Fully resolved values needed to render one systemd-networkd file."""

    device: str
    addresses: tuple[str, ...]
    dhcp: str | None
    dhcp_v4: "DHCPv4TemplateContext | None"
    ipv6_accept_ra: str | None
    link_local_addressing: str | None
    vlans: tuple[str, ...]
    bridge: str | None
    routes: tuple["RouteTemplateContext", ...]


@dataclass(frozen=True)
class RouteTemplateContext:
    """Native syntax values for one fully resolved static route."""

    destination: str
    gateway: str | None
    gateway_onlink: str | None


@dataclass(frozen=True)
class DHCPv4TemplateContext:
    """Explicit native DHCPv4 policy derived from Kavernis domain intent."""

    use_hostname: str
    send_hostname: str
    use_dns: str
    use_routes: str
    use_ntp: str
    route_metric: int | None


@dataclass(frozen=True)
class VlanNetdevTemplateContext:
    """Fully resolved values needed to render one VLAN .netdev file."""

    device: str
    tag: int


@dataclass(frozen=True)
class BridgeNetdevTemplateContext:
    """Fully resolved values needed to render one bridge .netdev file."""

    device: str
    stp: str


def generate(interfaces: Sequence[NetworkInterface]) -> NetworkdConfiguration:
    """Generate deterministic .network and virtual interface .netdev files."""
    ordered = sorted(interfaces, key=lambda item: item.id)
    children: dict[str, list[str]] = {interface.id: [] for interface in ordered}
    by_id = {interface.id: interface for interface in ordered}
    pairs: set[tuple[str, int]] = set()
    for interface in ordered:
        if interface.vlan is None:
            continue
        vlan = interface.vlan
        parent = by_id.get(vlan.parent)
        if (
            parent is None
            or parent.id == interface.id
            or parent.vlan is not None
            or parent.bridge is not None
        ):
            raise NetworkdValidationError(
                f"interface {interface.id}: invalid VLAN parent {vlan.parent}"
            )
        pair = (vlan.parent, vlan.tag)
        if pair in pairs:
            raise NetworkdValidationError(f"interface {interface.id}: duplicate VLAN")
        pairs.add(pair)
        children[vlan.parent].append(interface.device)

    bridges = _bridge_attachments(ordered)
    files: dict[str, str] = {}
    for interface in ordered:
        stem = f"10-kavernis-{interface.id}"
        files[f"{stem}.network"] = _render_interface(
            interface, children[interface.id], bridges.get(interface.id)
        )
        if interface.vlan is not None:
            vlan_context = VlanNetdevTemplateContext(
                device=interface.device, tag=interface.vlan.tag
            )
            files[f"{stem}.netdev"] = render_template(
                "interfaces/vlan.netdev.j2",
                asdict(vlan_context),
            )
        elif interface.bridge is not None:
            bridge_context = BridgeNetdevTemplateContext(
                device=interface.device,
                stp="yes" if interface.bridge.stp else "no",
            )
            files[f"{stem}.netdev"] = render_template(
                "interfaces/bridge.netdev.j2",
                asdict(bridge_context),
            )
    candidate = NetworkdConfiguration(files=files)
    validate(candidate)
    return candidate


def validate(candidate: NetworkdConfiguration) -> None:
    """Validate the generated networkd candidate before any future apply step.

    systemd-networkd has no standalone, side-effect-free syntax verifier for
    .network files. This validation therefore verifies the constrained native
    syntax generated by this backend. Native service validation belongs to the
    controlled integration/apply environment.
    """
    if not candidate.files:
        raise NetworkdValidationError(
            "networkd candidate must contain at least one file"
        )

    for filename, content in candidate.files.items():
        if not re.fullmatch(r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", filename):
            raise NetworkdValidationError(f"unsafe networkd filename: {filename}")
        if "/" in filename or "\\" in filename:
            raise NetworkdValidationError(f"unsafe networkd filename: {filename}")
        if filename.endswith(".netdev"):
            if "\nKind=bridge\n" in content:
                _validate_bridge_netdev(filename, content)
            else:
                _validate_vlan_netdev(filename, content)
        elif not content.startswith("[Match]\n") or "\n[Network]\n" not in content:
            raise NetworkdValidationError(f"invalid networkd content for {filename}")
        if not content.endswith("\n"):
            raise NetworkdValidationError(
                f"networkd content must end with newline: {filename}"
            )


def apply(
    candidate: NetworkdConfiguration,
    directory: Path = Path("/etc/systemd/network"),
) -> None:
    """Install a validated candidate and ask systemd-networkd to reload it.

    Only Kavernis-owned files are replaced or removed. If networkctl cannot
    activate the candidate, the previously managed files are restored before
    the error is reported.
    """
    validate(candidate)
    previous = _managed_files(directory)
    try:
        directory.mkdir(parents=True, exist_ok=True)
        for filename, content in candidate.files.items():
            _write_atomically(directory / filename, content)
        for filename in set(previous) - set(candidate.files):
            (directory / filename).unlink()
        subprocess.run(
            ["networkctl", "reload"], check=True, capture_output=True, text=True
        )
    except (OSError, subprocess.CalledProcessError) as error:
        _restore(directory, previous)
        try:
            subprocess.run(
                ["networkctl", "reload"], check=False, capture_output=True, text=True
            )
        except OSError:
            pass
        detail = str(error)
        if isinstance(error, subprocess.CalledProcessError):
            detail = str(error.stderr).strip()
        raise NetworkdApplyError(
            f"cannot apply networkd configuration: {detail}"
        ) from error


def artifact_hashes(candidate: NetworkdConfiguration) -> dict[str, str]:
    """Return deterministic SHA-256 hashes for a validated managed candidate."""
    validate(candidate)
    return {
        filename: hashlib.sha256(content.encode("utf-8")).hexdigest()
        for filename, content in sorted(candidate.files.items())
    }


def inspect_artifact_drift(
    expected_hashes: Mapping[str, str],
    directory: Path = Path("/etc/systemd/network"),
) -> tuple[ArtifactDrift, ...]:
    """Compare only Kavernis-owned networkd artifacts with applied hashes."""
    try:
        actual = _managed_files_bytes(directory)
    except OSError as error:
        raise NetworkdApplyError(
            f"cannot inspect networkd artifacts: {error}"
        ) from error
    drift: list[ArtifactDrift] = []
    for filename, expected_hash in sorted(expected_hashes.items()):
        contents = actual.pop(filename, None)
        if contents is None:
            drift.append(ArtifactDrift(filename, ArtifactDriftKind.MISSING))
        elif hashlib.sha256(contents).hexdigest() != expected_hash:
            drift.append(ArtifactDrift(filename, ArtifactDriftKind.MODIFIED))
    drift.extend(
        ArtifactDrift(filename, ArtifactDriftKind.UNEXPECTED)
        for filename in sorted(actual)
    )
    return tuple(drift)


def _managed_files(directory: Path) -> dict[str, str]:
    """Return only existing files owned by Kavernis."""
    if not directory.exists():
        return {}
    return {
        path.name: path.read_text(encoding="utf-8")
        for path in directory.iterdir()
        if path.is_file()
        and re.fullmatch(r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", path.name)
    }


def _managed_files_bytes(directory: Path) -> dict[str, bytes]:
    """Read managed artifacts as bytes for exact hash comparison."""
    if not directory.exists():
        return {}
    return {
        path.name: path.read_bytes()
        for path in directory.iterdir()
        if path.is_file()
        and re.fullmatch(r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", path.name)
    }


def _write_atomically(path: Path, content: str) -> None:
    """Replace one native configuration file without exposing partial content.

    Native networkd artifacts must be world-readable irrespective of the
    process umask, tempfile defaults, or an existing artifact's mode.
    """
    descriptor, temporary_name = tempfile.mkstemp(prefix=".kavernis-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.chmod(temporary_name, NETWORKD_FILE_MODE)
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _restore(directory: Path, previous: Mapping[str, str]) -> None:
    """Restore the managed-file snapshot after an unsuccessful activation."""
    if not directory.exists():
        return
    for path in directory.iterdir():
        if path.is_file() and re.fullmatch(
            r"10-kavernis-[a-z][a-z0-9-]*\.(network|netdev)", path.name
        ):
            path.unlink()
    for filename, content in previous.items():
        _write_atomically(directory / filename, content)


def _validate_vlan_netdev(filename: str, content: str) -> None:
    match = re.fullmatch(
        r"\[NetDev\]\nName=([A-Za-z0-9_.-]{1,15})\nKind=vlan\n\n"
        r"\[VLAN\]\nId=([0-9]+)\n",
        content,
    )
    if match is None or match[1] in {".", ".."} or not 1 <= int(match[2]) <= 4094:
        raise NetworkdValidationError(f"invalid VLAN netdev content for {filename}")


def _bridge_attachments(interfaces: Sequence[NetworkInterface]) -> dict[str, str]:
    """Resolve validated member ids to native bridge device names."""
    by_id = {interface.id: interface for interface in interfaces}
    vlan_parents = {
        interface.vlan.parent for interface in interfaces if interface.vlan is not None
    }
    attachments: dict[str, str] = {}
    for interface in interfaces:
        if interface.bridge is None:
            continue
        if interface.vlan is not None or not interface.bridge.members:
            raise NetworkdValidationError(f"interface {interface.id}: invalid bridge")
        for member_id in interface.bridge.members:
            member = by_id.get(member_id)
            if (
                member is None
                or member.bridge is not None
                or member_id in attachments
                or member_id in vlan_parents
                or member.ipv4.mode is not IPv4AddressMode.DISABLED
                or member.ipv6.mode is not IPv6AddressMode.DISABLED
            ):
                raise NetworkdValidationError(
                    f"interface {interface.id}: invalid bridge member {member_id}"
                )
            attachments[member_id] = interface.device
    return attachments


def _validate_bridge_netdev(filename: str, content: str) -> None:
    match = re.fullmatch(
        r"\[NetDev\]\nName=([A-Za-z0-9_.-]{1,15})\nKind=bridge\n\n"
        r"\[Bridge\]\nSTP=(yes|no)\n",
        content,
    )
    if match is None or match[1] in {".", ".."}:
        raise NetworkdValidationError(f"invalid bridge netdev content for {filename}")


def _render_interface(
    interface: NetworkInterface,
    vlans: Sequence[str] = (),
    bridge: str | None = None,
) -> str:
    """Resolve network intent into the limited context used by the template."""
    addresses: list[str] = []
    ipv6_accept_ra: str | None = None

    if interface.ipv4.mode is IPv4AddressMode.STATIC:
        if interface.ipv4.address is None:
            raise NetworkdValidationError(
                f"static IPv4 interface {interface.id} has no address"
            )
        addresses.append(str(interface.ipv4.address))

    if interface.ipv6.mode is IPv6AddressMode.STATIC:
        if interface.ipv6.address is None:
            raise NetworkdValidationError(
                f"static IPv6 interface {interface.id} has no address"
            )
        addresses.append(str(interface.ipv6.address))
        ipv6_accept_ra = "no"
    elif interface.ipv6.mode is IPv6AddressMode.SLAAC:
        ipv6_accept_ra = "yes"
    elif interface.ipv6.mode is IPv6AddressMode.DISABLED:
        ipv6_accept_ra = "no"

    dhcp: str | None = None
    dhcp_v4: DHCPv4TemplateContext | None = None
    if (
        interface.ipv4.mode is IPv4AddressMode.DHCP
        and interface.ipv6.mode is IPv6AddressMode.DHCP6
    ):
        dhcp = "yes"
    elif interface.ipv4.mode is IPv4AddressMode.DHCP:
        dhcp = "ipv4"
    elif interface.ipv6.mode is IPv6AddressMode.DHCP6:
        dhcp = "ipv6"

    if interface.ipv4.mode is IPv4AddressMode.DHCP:
        if interface.ipv4.dhcp is None:
            raise NetworkdValidationError(
                f"DHCP IPv4 interface {interface.id} has no DHCPv4 policy"
            )
        dhcp_v4 = DHCPv4TemplateContext(
            use_hostname="yes" if interface.ipv4.dhcp.use_hostname else "no",
            send_hostname="yes" if interface.ipv4.dhcp.send_hostname else "no",
            use_dns="yes" if interface.ipv4.dhcp.use_dns else "no",
            use_routes="yes" if interface.ipv4.dhcp.use_routes else "no",
            use_ntp="yes" if interface.ipv4.dhcp.use_ntp else "no",
            route_metric=interface.ipv4.dhcp.route_metric,
        )

    link_local_addressing: str | None = None
    if bridge is not None:
        dhcp = "no"
        link_local_addressing = "no"

    context = NetworkTemplateContext(
        device=interface.device,
        addresses=tuple(addresses),
        dhcp=dhcp,
        dhcp_v4=dhcp_v4,
        ipv6_accept_ra=ipv6_accept_ra,
        link_local_addressing=link_local_addressing,
        vlans=tuple(vlans),
        bridge=bridge,
        routes=tuple(
            RouteTemplateContext(
                destination=str(route.network),
                gateway=str(route.gateway_address) if route.gateway_address else None,
                gateway_onlink="yes" if route.gateway_onlink else None,
            )
            for route in interface.routes
        ),
    )
    return render_template("interfaces/network.j2", asdict(context))
